// DO NOT EDIT THIS FILE!!!
// DO NOT EDIT THIS FILE!!!
// DO NOT EDIT THIS FILE!!!

const Discord = require('discord.js');
const fs = require('fs');
const config = JSON.parse(fs.readFileSync('./database/config.json', 'utf8'));
const chalk = require('chalk');
const consolewords = chalk.keyword('white');
const consolecommands = chalk.keyword('cyan');
const consoleerrcmds = chalk.keyword('yellow');

module.exports = {
	name: 'deny',
	description: 'Denie the user\'s application',
	cooldown: 5,
	guildOnly: true,
	args: true,
	execute(message, args) {

		const tagUser = message.mentions.users.first();

		if (!tagUser) {
			const errorArgsEmbed = new Discord.MessageEmbed()
				.setColor('ORANGE')
				.setTitle(`⛔ Error (${config['bot'].prefix}appdenie) `)
				.setDescription(`<@${message.author.id}>, you didn't mention an user!\n\n**ID:** \`\`103\`\`\n**Usage:** \`\`${config['bot'].prefix}appdenie [@User]\`\`\n**Case ID:** \`\`4\`\`\n\n_If you think this is an error report it to an owner_`)
				.setTimestamp()
				.setFooter(`${config['bot'].factionname} Discord Bot`);
			message.channel.send({ embed: errorArgsEmbed });
			console.log(consolewords('[CMD]: ') + consoleerrcmds(`${message.author.username}: Missing Mention => Error => ID: 103, Case ID: 4`));
			return;
		}

		if (message.member.hasPermission([`${config['permissions'].deny}`])) {
			if (!args[0]) {
				const errorArgsEmbed = new Discord.MessageEmbed()
					.setColor('ORANGE')
					.setTitle(`⛔ Error (${config['bot'].prefix}appdenie) `)
					.setDescription(`<@${message.author.id}>, you missed some arguments!\n\n**ID:** \`\`103\`\`\n**Usage:** \`\`${config['bot'].prefix}appdenie [@User]\`\`\n**Case ID:** \`\`2\`\`\n\n_If you think this is an error report it to an owner_`)
					.setTimestamp()
					.setFooter(`${config['bot'].factionname} Discord Bot`);
				message.channel.send({ embed: errorArgsEmbed });
				console.log(consolewords('[CMD]: ') + consoleerrcmds(`${message.author.username}: Missing Arguments => Error => ID: 103, Case ID: 2`));
			}
			if (args[0]) {
				const demotion = new Discord.MessageEmbed()
					.setTitle(`${config['bot'].factionname} Application`)
					.setColor('RED')
					.setDescription(`Your application has been denied by \`\`${message.author.username}\`\`.`)
					.setTimestamp()
					.setFooter(`${config['bot'].factionname} Discord Bot`);
				tagUser.send({ embed: demotion });
				message.channel.send(`**${message.author.username}**, the user has been denied.`);
				console.log(consolewords('[CMD]: ') + consolecommands(`${message.author.username}: ${config['bot'].prefix}appdenie ${tagUser}`));
			}
		}
		else {
			const errorPermEmbed = new Discord.MessageEmbed()
				.setColor('ORANGE')
				.setTitle(`⛔ Error (${config['bot'].prefix}appdenie) `)
				.setDescription(`<@${message.author.id}>, you are not allowed to execute this command!\n\n**ID:** \`\`103\`\`\n**Needed Permission:** \`\`Recruitement Manager+\`\`\n**Case ID:** 1\n\n_If you think this is an error report it to an owner_`)
				.setTimestamp()
				.setFooter(`${config['bot'].factionname} Discord Bot`);
			message.channel.send({ embed: errorPermEmbed });
			console.log(consolewords('[CMD]: ') + consoleerrcmds(`${message.author.username}: Missing Permission => Error => ID: 103, Case ID: 1`));
		}
	},
};