// DO NOT EDIT THIS FILE!!!
// DO NOT EDIT THIS FILE!!!
// DO NOT EDIT THIS FILE!!!

const Discord = require('discord.js');
const fs = require('fs');
const config = JSON.parse(fs.readFileSync('./database/config.json', 'utf8'));
const chalk = require('chalk');
const consolewords = chalk.keyword('white');
const consolecommands = chalk.keyword('cyan');
const consoleerrcmds = chalk.keyword('yellow');

module.exports = {
	name: 'dm',
	description: 'Dm an user',
	guildOnly: true,
	args: true,
	cooldown: 5,
	execute(message, args) {

		const [atuser, ...restArgs] = args;
		const Messagecontent = restArgs.join(' ');
		const tagUser = message.mentions.users.first();

		if (!atuser) {
			const errorArgsEmbed = new Discord.MessageEmbed()
				.setColor('ORANGE')
				.setTitle(`⛔ Error (${config['bot'].prefix}dm) `)
				.setDescription(`<@${message.author.id}>, you didn't mention an user!\n\n**ID:** \`\`113\`\`\n**Usage:** \`\`${config['bot'].prefix}dm [@User] [Message]\`\`\n**Case ID:** \`\`4\`\`\n\n_If you think this is an error report it to an owner_`)
				.setTimestamp()
				.setFooter(`${config['bot'].factionname} Discord Bot`);
			message.channel.send({ embed: errorArgsEmbed });
			console.log(consolewords('[CMD]: ') + consoleerrcmds(`${message.author.username}: Missing Mention => Error => ID: 113, Case ID: 4`));
			return;
		}
		if (!Messagecontent) {
			const errorArgsEmbed = new Discord.MessageEmbed()
				.setColor('ORANGE')
				.setTitle(`⛔ Error (${config['bot'].prefix}dm) `)
				.setDescription(`<@${message.author.id}>, you missed some arguments!\n\n**ID:** \`\`113\`\`\n**Usage:** \`\`${config['bot'].prefix}dm [@User] [Message]\`\`\n**Case ID:** \`\`2\`\`\n\n_If you think this is an error report it to an owner_`)
				.setTimestamp()
				.setFooter(`${config['bot'].factionname} Discord Bot`);
			message.channel.send({ embed: errorArgsEmbed });
			console.log(consolewords('[CMD]: ') + consoleerrcmds(`${message.author.username}: Missing Arguments => Error => ID: 113, Case ID: 2`));
			return;
		}
		if (message.member.hasPermission([`${config['permissions'].dm}`])) {
			try {
				const dmembed = new Discord.MessageEmbed()
					.setTitle('Direct Message')
					.setColor('#2EFEF7')
					.setDescription(`You have been messaged.\n\n> **User**: \`\`${message.author.username}\`\`\n> **Recipient**: ${atuser}\n> **Message**: ${Messagecontent}`)
					.setTimestamp()
					.setFooter(`${config['bot'].factionname} Discord Bot`);
				tagUser.send({ embed: dmembed });
				message.channel.send('The direct message has been sent!');
			}
			catch {
				message.channel.send('The user needs to enable DM\'s');
			}
			console.log(consolewords('[CMD]: ') + consolecommands(`${message.author.username}: ${config['bot'].prefix}dm ${atuser} ${Messagecontent}`));
		}
		else {
			const errorPermEmbed = new Discord.MessageEmbed()
				.setColor('ORANGE')
				.setTitle(`⛔ Error (${config['bot'].prefix}dm) `)
				.setDescription(`<@${message.author.id}>, you are not allowed to execute this command!\n\n**ID:** \`\`105\`\`\n**Needed Permission:** \`\`${config['permissions'].dm}\`\`\n**Case ID:** 1\n\n_If you think this is an error report it to an owner_`)
				.setTimestamp()
				.setFooter(`${config['bot'].factionname} Discord Bot`);
			message.channel.send({ embed: errorPermEmbed });
			console.log(consolewords('[CMD]: ') + consoleerrcmds(`${message.author.username}: Missing Permission => Error => ID: 113, Case ID: 1`));
		}
	},
};
