// DO NOT EDIT THIS FILE!!!
// DO NOT EDIT THIS FILE!!!
// DO NOT EDIT THIS FILE!!!

const Discord = require('discord.js');
const fs = require('fs');
const config = JSON.parse(fs.readFileSync('./database/config.json', 'utf8'));
const chalk = require('chalk');
const consolewords = chalk.keyword('white');
const consolecommands = chalk.keyword('cyan');

module.exports = {
	name: 'help',
	description: 'Display info about this server',
	aliases: ['Help'],
	guildOnly: false,
	cooldown: 5,
	execute(message) {

		const exampleEmbed = new Discord.MessageEmbed()
			.setColor('DARK_GREEN')
			.setAuthor(`Asked by ${message.author.username}`, `${message.author.avatarURL()}`)
			.setTitle('HELP LIST')
			.addField('Commands', `\`\`${config['bot'].prefix}help\`\`\n\`\`${config['bot'].prefix}accept\`\`\n\`\`${config['bot'].prefix}denie\`\`\n\`\`${config['bot'].prefix}dm\`\`\n\`\`${config['bot'].prefix}restart\`\`\n\`\`${config['bot'].prefix}uptime\`\``, true)
			.addField('Info', 'Shows this\nAccept an user\'s app.\nDenie an user\'s app.\nDm an user\nRestart the bot\nCheck the current uptime', true)
			.setTimestamp()
			.setFooter(`${config['bot'].factionname} Discord Bot`);
		message.channel.send({ embed: exampleEmbed });
		message.delete();
		console.log(consolewords('[CMD]: ') + consolecommands(`${message.author.username}: ${config['bot'].prefix}help`));
	},
};