// DO NOT EDIT THIS FILE!!!
// DO NOT EDIT THIS FILE!!!
// DO NOT EDIT THIS FILE!!!

const Discord = require('discord.js');
const fs = require('fs');
const config = JSON.parse(fs.readFileSync('./database/config.json', 'utf8'));
const chalk = require('chalk');
const consolewords = chalk.keyword('white');
const consoleerrcmds = chalk.keyword('yellow');
const consolecommands = chalk.keyword('cyan');

module.exports = {
	name: 'restart',
	description: 'Restart the bot',
	guildOnly: true,
	id: 128,
	execute: async (message) => {

		if (message.member.hasPermission([`${config['permissions'].restart}`])) {
			try {
				const errorPermEmbed = new Discord.MessageEmbed()
					.setColor('GREEN')
					.setDescription('✅ Restarting...');
				await message.channel.send(errorPermEmbed);
				console.log(consolewords('[CMD]: ') + consolecommands(`${message.author.username}: ${config['bot'].prefix}restart`));
				process.exit(1);
			}
			catch (e) {
				return message.channel.send(`ERROR: ${e.message}`);
			}
		}
		else {
			const errorPermEmbed = new Discord.MessageEmbed()
				.setColor('ORANGE')
				.setTitle(`⛔ Error (${config['bot'].prefix}restart) `)
				.setDescription(`<@${message.author.id}>, you are not allowed to execute this command!\n\n**ID:** \`\`128\`\`\n**Needed Permission:** \`\`Owner\`\`\n**Case ID:** \`\`1\`\`\n\n_If you think this is an error report it to an owner_`)
				.setTimestamp()
				.setFooter(`${config['bot'].factionname} Discord Bot`);
			message.channel.send({ embed: errorPermEmbed });
			console.log(consolewords('[CMD]: ') + consoleerrcmds(`${message.author.username}: Missing Permission => Error => ID: 128, Case ID: 1`));
		}
	},
};